### ISSUE TITLE
2 part bug caused - restore from seed not working and messages not sending 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/loki-messenger-android#10]
**Describe the bug**
Restore from seed doesn't work. 
After clicking restore the public key is not correct for the seed that was entered and when checking the seed in settings a different seed is displayed. 
Also when loki-messenger is setup using restore from seed message are not able to be sent. 

**To reproduce**
Click restore from seed, enter seed and click restore. 

**Smartphone (please complete the following information):**
 - Device: Xperia xz2 premium 
 - OS: Android 9
 - messenger version 1.0.0 (first available on playstore)

**Comment by gmbnt** [comment]
Confirmed that seed restoration wasn't working correctly. This is fixed now and will be part of the next release (version 1.1.0).
