### ISSUE TITLE
you constantly monitoring what i typing?

### ISSUE THREAD

**Issue by onlineapps-cloud** [loki-project/loki-messenger-android#1704]
### Code of conduct

- [X] I have read and agree to adhere to the [Code of Conduct](https://github.com/oxen-io/session-android/blob/master/CODE_OF_CONDUCT.md)

### Self-training on how to write a bug report

- [X] I have learned [how to write a bug report](https://www.browserstack.com/guide/how-to-write-a-bug-report)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

question is, how you detect account seed phrase when i want to send it to someone? in my case i send it to myself, but how it's working?
i send to second account my seed phrase in this format: `"session: word1 word2 word3 ..."`
so my message starting with `session:` when i put message in text box i get this alert:
![session-attachment-2024-12-02-211816](https://github.com/user-attachments/assets/1de56cd7-f4a2-4cc5-b0a8-43bf4cc4568b)
how it's technically working? you constantly monitoring clipboard from my seed phrase? if yes, how you parse only seed phrase from another text?. where in the code is located this function? i want to see how it's looking this code that made this action.
Very strange action made your software.
i think that seed phrase is stored in plain text on the phone, to verify this action, but i don't understand how did you made matching of my random text + seed phrase with local seed phrase.

### Android Version

Android 14

### Session Version

1.20.2

**Comment by KeeJef** [comment]
Code is [here](https://github.com/oxen-io/session-android/blob/854ad892b268f10a5882426b69cc68a8f8647265/app/src/main/java/org/thoughtcrime/securesms/conversation/v2/ConversationActivityV2.kt#L1722), the device is just checking locally whether a message includes your seed and whether you are sending outside of "note to self" and surfacing this warning if you are. This check is local only, nothing gets transmitted to a server, its to try to prevent people sending their recovery password without understanding the risks. There isn't any monitoring of the clipboard for recovery phrases.
