### ISSUE TITLE
Typing '@' character crashes the messenger

### ISSUE THREAD

**Issue by Dormage** [loki-project/loki-messenger-android#48]
**Describe the bug**
In any chat, typing the character '@' causes the messenger app to either crash or become unresponsive

**To reproduce**
Type the '@' character in any chat.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Note 7, Motorola Moto G5
 - OS: Android Oreo, Android Pie
 - Version of Loki Messenger or latest commit hash

**Additional context**
Version 1.5.0 from Google Play.

**Comment by Mikunj** [comment]
Thanks for the report.
This should be fixed by PR #44 and will be in the next release.
