### ISSUE TITLE
Disconnect the Public Key string and the Display name from the same key press in settings.

### ISSUE THREAD

**Issue by Sonofotis** [loki-project/loki-messenger-android#6]
When you click the Public Key it pops up a menu for your display name. 

Have the display name disconnected with the public key.

![image](https://user-images.githubusercontent.com/39609800/61767967-3fdf4600-ae29-11e9-8ff4-cb12973c4429.png)

**Comment by gamabuntan** [comment]
Won't do this as we now have click to edit the display name and long press (or click share public key) to copy the public key
