### ISSUE TITLE
1.0.0-alpha.3 release is not an apk

### ISSUE THREAD

**Issue by kevinglasson** [loki-project/loki-messenger-android#8]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The alpha 3 release is not an apk file

### Steps to reproduce
Try to download alpha 3 release

**Actual result:** 
You can't directly install an app bundle file

**Expected result:** 
That the release would be an apk I could download and install on my phone

### Device info

**Device:** Pixel 3a XL

**Comment by gamabuntan** [comment]
This is intentional
